INSERT INTO biblioteca_development.books (title, summary, publishedDate, createdAt, updatedAt) VALUES ('Catcher in the Rye', "Holden Caulfield, a teenager, is living in an unspecified institution in Southern California near Hollywood in 1951. Caulfield intends to live with his brother D.B, an author and World War II veteran whom Holden resents for becoming a screenwriter, after his release in one month. As he waits, Holden recalls the events of the previous Christmas.

Holden begins his story at Pencey Preparatory Academy, an exclusive boarding school in Agerstown, Pennsylvania, on the Saturday afternoon of the traditional football game with a rival school. Holden has been expelled from Pencey due to poor work and is not to return after Christmas break, which begins the following Wednesday. He plans to return home on that day so that he will not be present when his parents receive notice of his expulsion. After forfeiting a fencing match in New York by forgetting the equipment aboard the subway, he is invited to the home of his history teacher, Mr. Spencer. Spencer is a well-meaning but long-winded old man. Spencer greets him and offers him advice, but embarrasses Holden by further criticizing Holden's work in his subject in a rude manner.

Holden returns to his dorm wearing the new red hunting cap he bought in New York. His dorm neighbor Robert Ackley is one of the few students also missing the game. Ackley, unpopular among his peers, disturbs Holden with his impolite questioning and mannerisms. Holden, who feels sorry for Ackley, tolerates his presence. Later, Holden agrees to write an English composition for his roommate, Ward Stradlater, who is leaving for a date. However, Holden is distressed to learn that Stradlater's date is an old friend, Jane Gallagher, whom Holden had romantic feelings for and feels protective of. That night, Holden decides to go to a Cary Grant comedy with his best friend Mal Brossard and Ackley. Since Ackley and Mal had already seen the film, they end up just playing pinball and returning to Pencey. When Stradlater returns hours later, he fails to appreciate the deeply personal composition Holden wrote for him about the baseball glove of Holden's late brother Allie, and refuses to reveal whether he slept with Jane. Enraged, Holden punches him, and Stradlater easily wins the ensuing fight. When Holden continues insulting him after the fight, Stradlater knocks him unconscious and leaves him with a bloody nose. After leaving for Ackley's room, Holden is disappointed when he treats him rudely. Fed up with the so-called 'phonies' at Pencey Prep, Holden impulsively decides to leave Pencey early, sells his typewriter to earn money, and catches a train to Penn Station in New York. Holden intends to stay away from his home in a hotel until Wednesday, when his parents would have received news of his expulsion. Aboard the train, Holden meets the mother of a wealthy, obnoxious Pencey student named Ernest Morrow, and lies to her about himself and her son.

In a taxicab, Holden inquires with the driver about whether the ducks in the Central Park lagoon migrate during winter, a subject he brings up often, but the man barely responds. Holden checks into the dilapidated Edmont Hotel. He spends an evening dancing with three tourist women from Seattle in the hotel lounge and enjoys dancing with one, though is disappointed that he is unable to hold a conversation with them. Following an unpromising visit to Ernie's Nightclub in Greenwich Village, Holden becomes preoccupied with his internal angst and agrees to have a prostitute named Sunny visit his room. His attitude toward the girl changes the minute she enters the room; she seems about the same age as him. Holden becomes uncomfortable with the situation, and when he tells her all he wants to do is talk, she becomes annoyed and leaves. Even though he still paid her the right amount for her time, she returns with her pimp Maurice and demands more money. Holden insults Maurice, and after Sunny takes the money from Holden's wallet, Maurice punches him in the stomach and leaves with Sunny. Afterwards, Holden imagines that he has been shot by Maurice, and pictures murdering him with an automatic weapon.

The next morning, Holden, becoming increasingly depressed and in need of personal connection, calls Sally Hayes, a familiar date. Although Holden claims that she is 'the queen of all phonies', they agree to meet that afternoon to attend a play at the Biltmore Theater. Holden shops for a special record, 'Little Shirley Beans', for his 10-year-old sister Phoebe. He spots a small boy singing 'If a body catch a body coming through the rye', which lifts his mood. Although Holden's date initially goes well, it soon sours after Sally introduces her friend George. After the play, Holden and Sally go ice skating at Rockefeller Center, where Holden suddenly begins ranting against society and frightens Sally. He impulsively invites Sally to run away with him that night to live in the wilderness of New England, but she is uninterested in his hastily conceived plan and declines. The conversation turns sour, and the two angrily part ways.

Holden decides to meet his old classmate, a Columbia student named Carl Luce, for drinks at the Wicker Bar in the Seton Hotel. During the meeting, Holden annoys Carl with his fixation on sex. After Luce leaves, Holden gets drunk, awkwardly flirts with several adults, and calls an icy Sally. Exhausted and out of money, Holden wanders over to Central Park to investigate the ducks, breaking Phoebe's record on the way. Nostalgically recalling his experience in elementary school and the unchanging dioramas in the Museum of Natural History that he enjoyed visiting as a child, Holden heads home to see Phoebe. He sneaks into his parents' apartment while they are out, and wakes up Phoebe – the only person with whom he seems to be able to communicate his true feelings. Although Phoebe is happy to see Holden, she quickly deduces that he has been expelled, and chastises him for his aimlessness and his apparent dislikes towards everything. When asked if he cares about anything, Holden shares a selfless fantasy he has been thinking about (based on a mishearing of Robert Burns's Comin' Through the Rye): he pictures himself as the sole guardian of thousands of children playing in a huge rye field on the edge of a cliff. His job is to catch the children if, in their abandon, they come close to falling off the brink; to be, in effect, the 'catcher in the rye'. Because of this misinterpretation, Holden believes that to be the 'catcher in the rye' means to save children from losing their innocence.

When his mother returns home, Holden slips out and visits his former and much-admired English teacher, Mr. Antolini, who is now a New York University professor. Mr. Antolini expresses concern that Holden is headed for 'a terrible fall' and advises him to begin applying himself. Although Holden is exhausted, he is courteous and considers his advice. Mr. Antolini also provides Holden a place to sleep. Holden is upset when he wakes up in the night to find Mr. Antolini patting his head, which he interprets as a homosexual advance. Confused and uncertain, he leaves and spends the rest of the night in a waiting room at Grand Central Station, where he sinks further into despair and expresses regret over leaving Mr. Antolini. He spends most of Monday morning wandering Fifth Avenue.

Losing hope of finding belonging or companionship in the city, Holden impulsively decides that he will head out west and live a reclusive lifestyle as a gas station attendant. He decides to see Phoebe at lunchtime to explain his plan and say farewell. While visiting Phoebe's school to give a forged excuse note, Holden becomes obsessed with graffiti containing the word 'fuck', and becomes distressed by the thought of children learning the word's meaning. When he meets Phoebe at the Metropolitan Museum of Art, she arrives with a suitcase and asks to go with him, even though she was looking forward to acting as Benedict Arnold in a play that Friday. Holden refuses to let her come with him, which upsets Phoebe, so Holden decides not to leave after all. He tries to cheer her up by allowing her to skip school and taking her to the Central Park Zoo, but she remains angry with him. They eventually reach the zoo's carousel, where Phoebe reconciles with Holden after he buys her a ticket. Holden is finally filled with happiness and joy at the sight of Phoebe riding in the rain.

In a short epilogue, Holden briefly alludes to encountering his parents that night and 'getting sick' (implying a tuberculosis diagnosis), mentioning that he will be attending another school in September. Holden says that he doesn't want to tell anything more because, surprisingly, he has found himself missing his former classmates. He warns the reader that telling others about their own experiences will lead them to miss the people who shared them.", '1951-07-16 00:00:00', now(), now());
INSERT INTO biblioteca_development.books (title, summary, publishedDate, createdAt, updatedAt) VALUES ('Dr Sleep', "Following the events of The Shining, after receiving a settlement from the owners of the Overlook Hotel, Danny Torrance remains psychologically traumatized as his mother Wendy slowly recovers from her injuries. Angry ghosts from the Overlook, including the woman from Room 217, still want to find Danny and eventually consume his phenomenal 'shining' power. Dick Hallorann, the Overlook's chef, teaches Danny to create lockboxes in his mind to contain the ghosts, including that of former Overlook owner Horace Derwent.

As an adult, Danny (now going by Dan) takes up his father's legacy of anger and alcoholism. Dan spends years drifting across the country, but he eventually makes his way to New Hampshire and decides to give up drinking. He settles in the small town of Frazier, working first at a tourist attraction and then at a hospice, and attending Alcoholics Anonymous meetings. His psychic abilities, long suppressed by his drinking, re-emerge and allow him to provide comfort to dying patients. Aided by a cat that can sense when someone is about to die, Dan acquires the nickname 'Doctor Sleep'.

In the meantime, Abra Stone, a baby girl born in 2001, begins to manifest psychic powers of her own when she seemingly predicts the September 11 terrorist attacks. She slowly and unintentionally establishes a telepathic bond with Dan; as she grows, the contact becomes more conscious and voluntary, and her shining grows stronger than his. One night, Abra psychically witnesses the ritual torture and murder of a boy by the True Knot, a group of quasi-immortals, many of which possess their own 'shine' abilities, who wander across America and periodically feed on 'steam', a psychic essence produced when the people who possess the shining die in pain. The True Knot's leader, Rose the Hat, becomes aware of Abra's existence and formulates a plan to kidnap Abra and keep her alive, so she can produce a limitless supply of steam.

The True Knot begin to die off from measles contracted from their last victim; they believe that Abra's steam can cure them. Abra asks for Dan's help, and he reveals his connection with Abra to her father David and their family doctor, John Dalton. Angry and skeptical at first, David starts to believe Dan and agrees to go along with his plan to save Abra. With the help of Billy Freeman, one of Dan's friends, they foil and kill a raiding party sent by Rose, led by Rose's lover Crow Daddy; however, Dan realizes that Rose will relentlessly hunt Abra for revenge. He visits Abra's great-grandmother Concetta, who is dying of cancer, and telepathically learns from her that he and Abra's mother Lucy are half-siblings with the same father. As Concetta dies, Dan takes her diseased steam into himself. Meanwhile, dissention in the ranks of The True Knot, along with Rose's obsession with Abra, leads to the group splitting up, leaving Rose with even fewer followers.

Following another kidnapping attempt that Abra foils with Dan's telepathic help, she baits Rose into confronting her at the location where the Overlook Hotel once stood in the Rocky Mountains in Colorado, now home to a campsite owned by the True Knot. Dan and Billy travel to the site, while Abra helps them by using her astral projection. Lying in wait, Dan releases the steam collected from Concetta to the remaining group of True Knot members, killing all of them. He frees the ghost of Horace Derwent to kill the last member, Silent Sarey, waiting to ambush him and Abra, and the two fight Rose in a long psychic struggle. With help from Billy and the ghost of Dan's father, Jack Torrance, they push Rose off an observation platform to her death. Before leaving the campsite, Dan makes peace with his father.

In the epilogue, Dan celebrates fifteen years of sobriety and attends Abra's fifteenth birthday party. He tells her about the patterns of alcoholism and violent behavior that run in his family, and warns her not to repeat them by starting to drink or submitting to rage. Abra agrees that she will behave, but before they can finish the conversation, Dan is called back to his hospice, where he comforts a dying colleague who had antagonized him in the past.", '2013-09-24 00:00:00', now(), now());
INSERT INTO biblioteca_development.books (title, summary, publishedDate, createdAt, updatedAt) VALUES ('City of Thieves', " The story is introduced as the recollections of the author's grandfather Lev, a contemporary Russian Jewish émigré. It is set in the first week of 1942, with Lev trying to survive the Siege of Leningrad after his father is 'disappeared' by the NKVD and his mother and sister flee the city. Lev is arrested for looting the body of an ejected Luftwaffe pilot. Thrown in prison, he meets Kolya Vlasov, a young Cossack soldier arrested for deserting his unit. The two are brought to Colonel Grechko of the NKVD who barters with them: if they are able to obtain a dozen eggs for the colonel's daughter's upcoming wedding, Lev and Kolya will be given their freedom. If they are unable to find the eggs (a luxury in the starving Leningrad), both will be executed.

During Lev and Kolya's search for the eggs, they meet a pair of cannibals and a boy in the black market selling 'library candy', food made from the bindings of books. They leave the city and go behind enemy lines. At the brink of death, Lev and Kolya encounter a small cottage hosting four young women, who are kept there by the German soldiers to rape at night. Lev and Kolya plot to attack the next Germans to come, and as they start their attack, an unseen group of Soviet partisans launches their own attack. Lev, Kolya, and Vika, a female partisan, venture into a poultry farm outside the city and allow themselves to be taken prisoner by the Germans. To gain the coveted dozen eggs, Lev must defeat a German officer of the Einsatzgruppen death squads in a game of chess. Lev wins the game and then kills the German with a knife he has hidden in his boot. He, Kolya, and Vika kill the other guards and escape.

Vika leaves to find another partisan group, but promises to find Lev after the war. As Lev and Kolya approach Leningrad on their way back, Kolya is shot by a Soviet soldier. He is taken to hospital but bleeds to death, while Lev discovers that the colonel had three dozen eggs airlifted in.

The epilogue is set three years later. Lev is in his apartment when Vika turns up, bringing him, as a joke, a carton of twelve eggs. She warns him that she does not cook, suggesting they later married, as at the start Lev's grandson says his grandmother would never cook.", '2008-01-01 00:00:00', now(), now());
INSERT INTO biblioteca_development.books (title, summary, publishedDate, createdAt, updatedAt) VALUES ('Flowers for Algernon', "Charlie Gordon, 32 years old, lives with phenylketonuria and demonstrates an IQ of 68. His uncle has arranged for him to hold a menial job at a bakery so that he will not have to live in a state institution. Desiring to improve himself, Charlie attends reading and writing classes at the Beekman College Center for Retarded Adults; his teacher is Miss Alice Kinnian. Two researchers at Beekman, Dr. Nemur and Dr. Strauss, are looking for a human test subject on whom to try a new surgical technique intended to increase intelligence. They have already performed the surgery on a mouse named Algernon, resulting in a dramatic improvement in his mental performance. Based on Alice's recommendation and his motivation to improve, Nemur and Strauss choose Charlie over smarter pupils to undergo the procedure.

The operation is a success, and within the next three months Charlie's IQ reaches 185. However, as his intelligence, education, and understanding of the world increase, his relationships with people deteriorate. His co-workers at the bakery, who used to amuse themselves at his expense, now fear and resent his increased intelligence and persuade his boss to fire him. Later, Charlie confronts his scientific mentors about their condescending attitude toward him, particularly Dr. Nemur, because Charlie believed Dr. Nemur considered him a mere laboratory subject and not human before the operation.

When not drinking at night, Charlie spends weeks continuing his mentors' research and writing reports which include observations of Algernon, whom he keeps at his apartment. Charlie's research discovers a flaw in the theory behind Nemur and Strauss's intelligence-enhancing procedure that could cause him to revert to his original mental state. His conclusions prove true when Algernon starts behaving erratically, loses his own enhanced intelligence, and dies.

Charlie tries to mend the long-broken relationships with his parents, even as his own intelligence enhancements begin to slip away. He remembers as a boy his mother insisted on his institutionalization, overruling his father's wish to keep him in the household. His mother, who still lives in the family's old home in Brooklyn, has developed dementia and recognizes him only briefly; his father, who broke off contact with the family years earlier, does not recognize him at all. He is only able to reconnect with his now-friendly younger sister, Norma, who had hated him for his mental disability when they were growing up, and is now caring for their mother in their newly depressed neighborhood. When Norma asks Charlie to stay with his family, he refuses but promises to send her money.

Despite regressing to his former self, he remembers he was once a genius. He cannot bear to have his friends and co-workers pity him. He decides to live at the state-sponsored Warren Home School, where nobody knows about the operation. In a final postscript to his writings, he requests that someone put some flowers on Algernon's grave in Charlie's former backyard.", '1959-04-01 00:00:00', now(), now());
INSERT INTO biblioteca_development.books (title, summary, publishedDate, createdAt, updatedAt) VALUES ('Cien años de soledad', "One Hundred Years of Solitude is the story of seven generations of the Buendía Family in the town of Macondo. The founding patriarch of Macondo, José Arcadio Buendía, and Úrsula Iguarán, his wife (and first cousin), leave Riohacha, Colombia, after Arcadio kills Prudencio Aguilar after a cockfight, for suggesting Arcadio was impotent. One night of their emigration journey, while camping on a riverbank, José Arcadio Buendía dreams of 'Macondo', a city of mirrors that reflected the world in and about it. Upon awakening, he decides to establish Macondo at the riverside; after days of wandering the jungle, José Arcadio Buendía's founding of Macondo is utopic.[3]

Founding patriarch José Arcadio Buendía believes Macondo to be surrounded by water, and from that island, he invents the world according to his perceptions.[3] Soon after its foundation, Macondo becomes a town frequented by unusual and extraordinary events that involve the generations of the Buendía family, who are unable or unwilling to escape their periodic (mostly self-inflicted) misfortunes. For years the town is solitary and unconnected to the outside world with the exception of the annual visit of a band of gypsies, who show the townspeople technology such as magnets, telescopes and ice. The leader of the gypsies, a rough man named Melquiades, maintains a close friendship with José Arcadio Buendía who becomes increasingly withdrawn, obsessed with investigating the mysteries of the universe presented to him by the gypsies. Ultimately he is driven insane, speaking only in Latin, and is tied to a chestnut tree by his family for many years until his death.

Eventually Macondo becomes exposed to the outside world and the government of newly-independent Colombia. A rigged election between the Conservative and Liberal parties is held in the town, inspiring Aureliano Buendía to join a civil war against the Conservative government. He becomes an iconic revolutionary leader, fighting for many years and surviving multiple attempts on his life, but ultimately becomes tired of war and signs a peace treaty with the Conservatives. Disillusioned, he returns to Macondo and spends the rest of his life making tiny goldfish out of gold in his workshop.

The railroad comes to Macondo, bringing in new technology and many foreign settlers. An American fruit company constructs a banana plantation outside the town and builds their own segregated village across the river. This ushers in a period of prosperity that ends in tragedy as thousands of striking plantation workers are massacred by the Colombian army, an incident based on the real life Banana Massacre of 1928. José Arcadio Segundo, the only survivor of the massacre, finds no evidence of the massacre and the surviving townspeople refusing to believe that it happened.

By the novel's end Macondo has fallen into a decrepit and near-abandoned state, with the only remaining Buendías being Amaranta Úrsula and her nephew Aureliano. Aureliano's parentage is hidden by his grandmother Fernanda, and he and Amaranta Úrsula enter an incestuous relationship unknowingly. They have a child who bears the tail of a pig, fulfilling the lifelong fear of the long-dead matriarch Úrsula. Amaranta Úrsula dies in childbirth and the child is devoured by ants, leaving Aureliano the last member of the family. He decodes an encryption left behind in a manuscript by Melquiades generations ago. The secret message informs the recipient of every fortune and misfortune lived by the Buendía family's generations. As he reads the manuscript, a hurricane destroys all trace of Macondo's existence.", '1967-05-30 00:00:00', now(), now());
INSERT INTO biblioteca_development.books (title, summary, publishedDate, createdAt, updatedAt) VALUES ('For Whom the Bell Tolls', "The novel graphically describes the brutality of the civil war in Spain during this time. It is told primarily through the thoughts and experiences of the protagonist, Robert Jordan. It draws on Hemingway's own experiences in the Spanish Civil War as a reporter for the North American Newspaper Alliance.[11]

Jordan is an American who had lived in Spain during the pre-war period, and fights as an irregular soldier for the Republic against Francisco Franco's fascist forces. An experienced dynamiter, he is ordered by a Russian general to travel behind enemy lines and destroy a bridge with the aid of a band of local anti-fascist guerrillas, in order to prevent enemy troops from responding to an upcoming offensive. On his mission, Jordan meets the rebel Anselmo who brings him to the hidden guerrilla camp and initially acts as an intermediary between Jordan and the other guerrilla fighters.

In the camp, Jordan encounters María, a young Spanish woman whose life had been shattered by her parents' execution and her rape at the hands of the Falangists (part of the fascist coalition) at the outbreak of the war. His strong sense of duty clashes with both the unwillingness of the guerrilla leader Pablo to commit to an operation that would endanger himself and his band, and Jordan's own new-found lust for life which arises from his love for María. Pablo's wife, Pilar, with the support of the other guerillas, displaces Pablo as the group leader and pledges the allegiance of the guerrillas to Jordan's mission. When another band of anti-fascist guerrillas, led by El Sordo, is surrounded and killed during a raid they conducted in support of Jordan's mission, Pablo steals the dynamite detonators and exploder, hoping to prevent the demolition and thereby avoid fascist reprisals. Although he disposes of the detonators and exploder by throwing them down a gorge into the river, Pablo regrets abandoning his comrades and returns to assist in the operation.

The enemy, apprised of the coming offensive, has prepared to ambush it in force and it seems unlikely that the blown bridge will do much to prevent a rout. Regardless of this, Jordan understands that he must still demolish the bridge unless he receives explicit orders not to. Lacking the detonation equipment stolen by Pablo, Jordan plans an alternative method to explode the dynamite by using hand grenades with wires attached so that their pins can be pulled from a distance. This improvised plan is considerably more dangerous because the men must be nearer to the explosion. While Pilar, Pablo, and other guerrilla members attack the posts at the two ends of the bridge, Jordan and Anselmo plant and detonate the dynamite, costing Anselmo his life when he is hit by a piece of shrapnel. While escaping, Jordan is maimed when a tank shoots his horse out from under him. Knowing that his wound is severe enough that he is highly unlikely to survive, and that he would slow the others down, he bids goodbye to María and ensures that she escapes to safety with the surviving guerrillas. He refuses an offer from Agustín to shoot him and lies in agony, hoping to kill an enemy officer and delay their pursuit of his comrades before dying. The narrative ends right before Jordan launches his ambush.", '1940-10-21 00:00:00', now(), now());

